### ISSUE TITLE
Speaker-Tag: Lenz, die Soldaten

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/metadata#1]
In dem Drama "Sie Soldaten" von Lenz rhtz.0  redet die Figur des Obristen, in der dramatis personae genannt "Graf von Spannheim, sein Obrister" einmal als OBRIST, als OBRISTE und als OBRISTER. Das ist die gleiche Figur.
Sie redet nie als "Spannheim"

**Comment by nilsreiter** [comment]
Das können wir im Prinzip schon über "speaker assignment rules" lösen. In [speaker-assignment-mapping.csv](quadrama/metadata/blob/master/speaker-assignment-mapping.csv) könnte man das eintragen, allerdings wird das nur nach dem nächsten Datendurchlauf aktiv.

**Comment by nilsreiter** [comment]
Ha, das hat sogar schon jemand eingetragen 👍
