### ISSUE TITLE
GATTUNGSFRAGE--interessante Fälle

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/metadata#3]
Frage: Wie lassen sich stücke Gattungen zuordnen, die "Drama" oder "Schauspiel" heißen, bei denen oft der Autor bewusst keine Gattung (Komödie / Tragödie) wählt.

Fall 1) Kleists mittlere / spätere Stücke (ohne Gattungszuordnung)

Fall 2) t9qb_0

Christian Reuter Lamaladie & Lamort de L'Honnete Femme. Das ist: Der ehrlichen Frau chlampampe Krankheit und Tod. In einem Lust- und Trauer- spiele vorgestellet und aus dem Französischen in das Teutsche übergesetzt von Schelmuffsky Reise-Gefährten

Weitere Fälle:
"https://quadrama.github.io/assets/2016-10-07-ottokar-capulet/cluster-analysis.pdf 
  In 149 von 181 Fällen liegt die Analyse richtig. Die wenigen fehlerhaften Rubrizierungen sind i.d.R mit Blick auf die Texte gut erklärbar: So sind einige Texte dramatische Mischformen, wie etwa Hebbels „Märchen-Lustspiel“ **Der Rubin (1851)** oder die als Komödie gekennzeichnete bitterböse Satire von Prutz **Die politische Wochenstube** (1845), die zu einer Anklage wegen Majestätsbeleidigung führte. 
  Zum Autorsignal in der stilometrischen Autorschaftsattribution s. Jannidis 2014.
  Spearman, 1904."
(Fußnote aus Kleist-JB-Aufsatz

**Comment by marcuswilland** [comment]
Interessant: 
https://github.com/quadrama/Kleist/blob/master/Plots/Shakespeare-Gattung.png

die Gattungszuordnung bei Romeo und Julia unterscheidet sich bei vers/prosa-Übersetzung. **WARUM?**

**Comment by nilsreiter** [comment]
Hier steht noch was zu Gattungen: https://github.com/quadrama/DramaAnalysis/wiki/Gattungsanalysen

**Comment by nilsreiter** [comment]
Der Unterschied bei der Gattung von Vers/Prosa-RuJ ist ja nicht groß, wahrscheinlich ist das eher ein Artefakt der Methode. Da diese Gattungsbegriffe sich ja auch von der Wortart her unterscheiden interagiert das mit linguistischen Texteigenschaften.

**Comment by nilsreiter** [comment]
https://clarin06.ims.uni-stuttgart.de/quadrama/quadrama/issues/3
